name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
        - rust-target: aarch64-apple-darwin
          label: aarch64
        - rust-target: x86_64-apple-darwin
          label: x86-64
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.rust-target }}
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        key: build
    - name: Build
      run: cargo build --all --verbose --locked --target ${{ matrix.rust-target }}
    - name: Test
      run: cargo test --locked --target ${{ matrix.rust-target }}