name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: "macos-latest"
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        key: debug_aarch64-apple-darwin
    - name: Build
      run: cargo build --verbose --locked
    - name: Run tests
      run: cargo test --verbose --locked