name: Coverage

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - run: rustup toolchain install stable --profile minimal
    - run: cargo install --locked cargo-tarpaulin
    - run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        fail_ci_if_error: true