name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: Update formula
        uses: IohannRabeson/update-homebrew-formula@2dc9a59aa0a534f3409bf86d7947d9119e8c8cc0
        with:
          formula-name: tmignore-rs
          tap-repository: IohannRabeson/homebrew-tap
          tap-token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          version: ${{ github.ref_name }}
          revision: ${{ github.sha }}